apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wasteco

resources:
  - ../../base
  - tailscale-svc.yaml
  - ingress.yaml

secretGenerator:
  - name: wasteco-secret
    envs:
      - .env

images:
  - name: ghcr.io/faisalaffan/community-waste-collection-api
    newTag: dev

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: wasteco-api
