apiVersion: v1
kind: Secret
metadata:
  name: wasteco-secret
  namespace: wasteco
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres_super_secret_2026"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"
